# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Full"
position = { x = 10, y = 10 }
dimensions = { columns = 120, lines = 80 }

[window.padding]
x = 7
y = 0

[shell]
program = "/usr/bin/tmux"
args = ["new", "-A", "-D", "-s", "main"]
