# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Full"
position = { x = 10, y = 10 }
dimensions = { columns = 120, lines = 80 }

[window.padding]
x = 7
y = 0

[shell]
program = "/usr/bin/tmux"

#adding mouse and scrolling params below to gain copy scroll for more than one effin screen in tmux
[mouse]
hide_when_typing = false

[scrolling]
history = 0
