#!/bin/bash
echo -e "\nUpdating packages...\n"
sleep 2
sudo apt update -y && sudo apt upgrade -y
#echo -e "\nRemoving unused packages...\n"
#sleep 2
#sudo apt autoremove -y && sudo apt clean -y
sleep 2
echo -e "\nComplete.\n"
